name: Deploy to Raspberry Pi

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Setup Node (fnm)
        run: | 
          echo "$HOME/.local/share/fnm" >> "$GITHUB_PATH"
          export PATH="$HOME/.local/share/fnm:$PATH"
          fnm use --install-if-missing 22.12.0
          fnm default 22.12.0
          echo "$HOME/.local/share/fnm/aliases/default/bin" >> "$GITHUB_PATH"

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          sudo mkdir -p /var/www/fimbulfamb_frontend
          sudo rsync -a --delete build/ /var/www/fimbulfamb_frontend/

      - name: Restart service
        run: sudo systemctl restart nginx
